import { User } from "@prisma/client";
import prisma from "../../prismaClient";
import { Request, Response } from "express";
import { AuthenticatedRequest } from "../../middleware/auth";
import nodemailer from "nodemailer";

/**
 * Creates a new MFA token for the specified user.
 * @param user - The user for whom to create the MFA token
 * @returns The newly created MFA token string
 */
export const mfaEmailToken = async (req: Request, res: Response) => {
  try {
    // Validated the request user
    const authReq = req as AuthenticatedRequest;
    if (!authReq.user) {
      return res.status(401).json({
        message: "Unauthorized",
      });
    }

    // Create a new token for the user
    const token = await mfaCreateToken(authReq.user);

    // Email the token to the user's email address
    const emailResponse = await emailMfaToken(authReq, token);

    // Successfully return the email response
    return res.status(200).json({
      emailResponse,
    });
  } catch (error) {
    console.error("Error creating MFA token:", error);
    return res.status(500).json({
      message: "An error occurred while creating MFA token",
    });
  }
};

/**
 * Creates a new MFA token for the specified user.
 * Deletes any existing tokens for the user first.
 * Note: We're not using upsert here as the token is generated by the database.
 * @param user - The user for whom to create the MFA token
 * @returns The newly created MFA token string
 */
const mfaCreateToken = async (user: User) => {
  // Delete any existing token for the user first
  await prisma.token.deleteMany({
    where: {
      userId: user.id,
    },
  });

  // Create a new token for the user
  const token = await prisma.token.create({
    data: {
      userId: user.id,
    },
  });
  return token.token;
};

/**
 * Verifies the MFA token and returns the associated user if valid.
 * @param token - MFA token to verify
 * @returns the associated user if the token is valid
 */
export const verifyMfaToken = async (token: string) => {
  // Find the token and associated user
  const tokenRecord = await prisma.token.findUnique({
    where: { token },
    include: { user: true },
  });

  // Check if token exists
  if (!tokenRecord) {
    throw new Error("Token not found");
  }

  // Check if token is expired and return user if valid
  const now = new Date();
  if (tokenRecord.expiresAt < now) {
    throw new Error("Token has expired");
  }

  return tokenRecord.user;
};

/**
 * Deletes the specified MFA token.
 * @param token - MFA token to delete
 */
export const deleteMfaToken = async (token: string) => {
  // Delete the token from the database
  await prisma.token.delete({
    where: { token },
  });
};

export const sendMfaToken = async (req: Request, res: Response) => {
  try {
    // Validated the request user
    const authReq = req as AuthenticatedRequest;
    if (!authReq.user) {
      return res.status(401).json({
        message: "Unauthorized",
      });
    }

    // Create a new token for the user
    const token = await mfaCreateToken(authReq.user);

    // Successfully return the email response
    return res.status(200).json({
      token,
    });
  } catch (error) {
    console.error("Error sending MFA token:", error);
    return res.status(500).json({
      message: "An error occurred while sending MFA token",
    });
  }
};

/**
 * Sends an MFA token to the user's email using AWS SES via nodemailer.
 * @param authReq - The authenticated request containing user information
 * @param token - The MFA token to send
 * @returns Email send response
 */
const emailMfaToken = async (authReq: AuthenticatedRequest, token: string) => {
  // Create a nodemailer transporter using AWS SES
  const transporter = nodemailer.createTransport({
    host: "email-smtp.us-east-1.amazonaws.com", // Replace with your AWS SES region
    port: 587,
    secure: false, // Use STARTTLS
    auth: {
      user: process.env.AWS_SES_SMTP_USERNAME, // Your AWS SES SMTP username
      pass: process.env.AWS_SES_SMTP_PASSWORD, // Your AWS SES SMTP password
    },
  });

  // Define email options
  const mailOptions = {
    from: process.env.FROM_EMAIL || "noreply@yourapp.com", // Verified email address in SES
    to: authReq.user!.email,
    subject: "Your MFA Token - PM Board",
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #333;">Your MFA Token</h2>
        <p>Hello ${authReq.user!.name},</p>
        <p>You have requested an MFA token for your PM Board account. Your token is:</p>
        <div style="background-color: #f4f4f4; padding: 20px; text-align: center; margin: 20px 0; border-radius: 5px;">
          <h1 style="color: #007bff; letter-spacing: 2px; margin: 0;">${token}</h1>
        </div>
        <p><strong>Important:</strong> This token will expire in 5 minutes for security reasons.</p>
        <p>If you did not request this token, please ignore this email.</p>
        <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
        <p style="color: #666; font-size: 12px;">
          This is an automated email from PM Board. Please do not reply to this email.
        </p>
      </div>
    `,
    text: `
Hello ${authReq.user!.name},

You have requested an MFA token for your PM Board account. Your token is: ${token}

Important: This token will expire in 5 minutes for security reasons.

If you did not request this token, please ignore this email.

This is an automated email from PM Board. Please do not reply to this email.
    `.trim(),
  };

  try {
    // Send the email
    const result = await transporter.sendMail(mailOptions);

    return {
      success: true,
      messageId: result.messageId,
      message: `MFA token sent successfully to ${authReq.user!.email}`,
    };
  } catch (error) {
    console.error("Error sending MFA token email:", error);
    throw new Error(
      `Failed to send MFA token email: ${
        error instanceof Error ? error.message : "Unknown error"
      }`
    );
  }
};
